image: python:3.9

stages:
  - deploy

variables:
  PYTHONPATH: "/usr/local/lib/python3.9/site-packages"

before_script:
  - pip install -r requirements.txt

deploy_production:
  stage: deploy
  script:
    - pip install paramiko
    - python deploy_script.py
  only:
    - main
