stages:
  - build
  - test
  - deploy

variables:
  VENV_PATH: "venv"

before_script:
  - python -m venv $VENV_PATH
  - source $VENV_PATH/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Building the application..."

test:
  stage: test
  script:
    - pytest

deploy:
  stage: deploy
  script:
    - echo "Deploying to server..."
    - scp -r * $DEPLOY_SERVER:$DEPLOY_PATH
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && source $VENV_PATH/bin/activate && pip install -r requirements.txt && nohup python your_app.py > app.log 2>&1 &"
  only:
    - main
