image: python:3.12

stages:
  - build
  - test
  - deploy

variables:
  VENV_PATH: "myenv"

before_script:
  - apt-get update && apt-get install -y python3-venv
  - python3 -m venv $VENV_PATH
  - source $VENV_PATH/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Building the application..."

test:
  stage: test
  script:
    - source $VENV_PATH/bin/activate  # Aktifkan virtual environment
    - pip freeze  # Tampilkan paket yang terinstal untuk memeriksa apakah pytest terinstal
    - which pytest  # Periksa lokasi pytest
    - pytest --maxfail=1 --disable-warnings -v

deploy:
  stage: deploy
  script:
    - echo "Deploying to server..."
    - chmod 600 ~/.ssh/id_rsa  # Set permissions on the private key
    - ssh-add ~/.ssh/id_rsa <<< "$SSH_PASSPHRASE"  # Add the private key to SSH agent
    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts  # Add the server to known hosts
    - scp -i ~/.ssh/id_rsa -r * $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH  # Securely copy files to the server
    - ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_SERVER << 'EOF'
        echo "Connected to server"
        ls -la $DEPLOY_PATH
        cd $DEPLOY_PATH
        
        if [ ! -d "$VENV_PATH" ]; then
          echo "Creating virtual environment..."
          python3 -m venv $VENV_PATH
        fi
        
        source $VENV_PATH/bin/activate
        
        echo "Installing dependencies..."
        pip install -r requirements.txt
        
        echo "Starting application..."
        nohup uvicorn app.main:app --host 0.0.0.0 --port 8005 > app.log 2>&1 &
        
        echo "Deployment complete"
      EOF
  only:
    - dev


