stages:
  - build
  - test
  - deploy

variables:
  VENV_PATH: "venv"

before_script:
  - python -m venv $VENV_PATH
  - source $VENV_PATH/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Building the application..."

test:
  stage: test
  script:
    - pytest

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - # Tambahkan skrip deployment Anda di sini
  only:
    - main
