image: python:3.12

stages:
  - build
  - test
  - deploy

before_script:
  - apt-get update && apt-get install -y python3-venv
  - python3 -m venv $VENV_PATH
  - source $VENV_PATH/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Building the application..."

test:
  stage: test
  script:
    - source $VENV_PATH/bin/activate  # Aktifkan virtual environment
    - pip freeze  # Tampilkan paket yang terinstal untuk memeriksa apakah pytest terinstal
    - which pytest  # Periksa lokasi pytest
    - pytest --maxfail=1 --disable-warnings -v

deploy:
  stage: deploy
  script:
    - echo "Deploying to server..."
    - scp -r * $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
    - ssh $DEPLOY_USER@$DEPLOY_SERVER << 'EOF'
        # Buat virtual environment dan aktifkan
    - python3 -m venv $VENV_PATH
    - source $VENV_PATH/bin/activate
        
        # Pindah ke direktori deploy
    - cd $DEPLOY_PATH
        
        # Install dependencies
    - pip install -r requirements.txt
        
        # Jalankan aplikasi dengan uvicorn
    - nohup uvicorn app.main:app --host 0.0.0.0 --port 8005 > app.log 2>&1 &
      EOF
  only:
    - main
