image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  SERVER_IP: "$SERVER_IP"
  SFTP_USERNAME: "$SFTP_USERNAME"
  SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY"
  PASSPHRASE: "$PASSPHRASE"
  SPACES_ENDPOINT: "$SPACES_ENDPOINT"
  SPACES_BUCKET: "$SPACES_BUCKET"
  SPACES_FOLDER: "$SPACES_FOLDER"
  SPACES_ACCESS_KEY: "$SPACES_ACCESS_KEY"
  SPACES_SECRET_KEY: "$SPACES_SECRET_KEY"
  DEPLOY_SERVER: "$DEPLOY_SERVER"  # Menambahkan DEPLOY_SERVER sebagai variabel

cache:
  paths:
    - .cache/pip

before_script:
  - python --version
  - pip --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - test
  - run
  - deploy

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install ruff tox
    - pip install --editable ".[test]"
    - tox -e py,ruff

run:
  stage: run
  script:
    - pip install -r requirements.txt
    - python app/main.py  # Pastikan command ini sesuai untuk menjalankan aplikasi Anda
  artifacts:
    paths:
      - build/*

deploy:
  stage: deploy
  script:
    - echo "Deploying to production environment..."
    - apt-get update && apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - scp -o StrictHostKeyChecking=no -r . $SFTP_USERNAME@$DEPLOY_SERVER:/home/peratan/bot_telagram
    - ssh -o StrictHostKeyChecking=no $SFTP_USERNAME@$DEPLOY_SERVER "cd /home/peratan/bot_telagram && ./deploy_script.sh"
  environment:
    name: production
  only:
    - main  # Branch utama Anda, di sini 'main'
