[tool.poetry]
name = "bo_telegram"
version = "0.1.0"
description = "Bot Telegram"
authors = ["Farihul Rouf <rouf@optimasi.ai>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
